services:
  tests:
    container_name: antifraud-tests
    restart: no
    build:
        dockerfile: tests.Dockerfile
    command: ["pytest", "-vvv"]
    environment:
      - ADMIN_EMAIL=admin@mail.ru
      - ADMIN_FULLNAME=Test Test
      - ADMIN_PASSWORD=123123123aA!
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=testdb_test
      - RANDOM_SECRET=Jf/ZpZSxfMWnOexP48Mp1z200jd+8BVZ7ws6Uw5Jp/w=
      - DB_USER=testuser
      - DB_PASSWORD=testpass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_URL=http://antifraud-tests-backend:8080/api/v1/
    depends_on:
      backend:
          condition: service_healthy
  postgres:
    container_name: antifraud-tests-postgres
    extends:
      file: compose.base.yaml
      service: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=testdb_test
  backend:
    container_name: antifraud-tests-backend
    extends:
      file: compose.base.yaml
      service: backend
    environment:
      - ADMIN_EMAIL=admin@mail.ru
      - ADMIN_FULLNAME=Test Test
      - ADMIN_PASSWORD=123123123aA!
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=testdb_test
      - RANDOM_SECRET=Jf/ZpZSxfMWnOexP48Mp1z200jd+8BVZ7ws6Uw5Jp/w=
      - DB_USER=testuser
      - DB_PASSWORD=testpass
      - REDIS_HOST=redis
      - REDIS_PORT=6379