services:
  postgres:
    image: postgres:16-alpine
    restart: always
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    container_name: antifraud-backend
    build:
        dockerfile: local-run.Dockerfile
    expose:
      - 8080:8080
    command: [ "backend", "run", "api"]
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - "./src/backend/infrastructure/database/alembic/migrations/versions/:/home/app/src/backend/infrastructure/database/alembic/migrations/versions/"
