services:
  db:
    container_name: antifraud-db
    image: postgres
    restart: always
    user: postgres
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
  backend:
    container_name: antifraud-backend
    build:
      context: .
    expose:
      - 5000
    command: [ "backend", "run", "api"]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "./src/backend/infrastructure/database/alembic/migrations/versions/:/home/app/src/backend/infrastructure/database/alembic/migrations/versions/"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_NAME=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RANDOM_SECRET=jwtttttttultttraamegggaaa_key?OfTheSuper1SecretTOKENOFTHETOKEN?!!
      - ADMIN_EMAIL=example@example.com
      - ADMIN_FULLNAME=Ultra Admin
      - ADMIN_PASSWORD=12345!
  redis:
    container_name: antifraud-project-redis
    image: redis
    ports:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=0