class ApplicationError(Exception): ...


class ForbiddenError(ApplicationError): ...


class NotFoundError(ApplicationError): ...


class InvalidPaginationQueryError(ApplicationError): ...


class UnauthorizedError(ApplicationError): ...
