"""merchant_id nullable

Revision ID: 292f2cdb2305
Revises: e5c619e07740
Create Date: 2026-01-25 20:22:50.518131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '292f2cdb2305'
down_revision: Union[str, Sequence[str], None] = 'e5c619e07740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_table', 'merchant_category_code',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_table', 'merchant_category_code',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    # ### end Alembic commands ###
