"""tr nullable

Revision ID: 7864eed1ffc8
Revises: 292f2cdb2305
Create Date: 2026-01-25 20:40:04.784734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7864eed1ffc8'
down_revision: Union[str, Sequence[str], None] = '292f2cdb2305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_table', 'merchant_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('transaction_table', 'ip_address',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('transaction_table', 'device_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('transaction_table', 'channel',
               existing_type=postgresql.ENUM('WEB', 'MOBILE', 'POS', 'OTHER', name='transactionchannel'),
               nullable=True)
    op.alter_column('transaction_table', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_table', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('transaction_table', 'channel',
               existing_type=postgresql.ENUM('WEB', 'MOBILE', 'POS', 'OTHER', name='transactionchannel'),
               nullable=False)
    op.alter_column('transaction_table', 'device_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('transaction_table', 'ip_address',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('transaction_table', 'merchant_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
